## DAV 5400 Module 3 Assignment
### By Aishwarya Deshmane

### 1. Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays
Import numpy library

np.intersect1d(a,b) gives 1D sorted array of common and unique elements

Assign the result array to variable c

Print the result

In [1]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

c = np.intersect1d(a,b)
c

array([2, 4])

### 2. Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value
np.arange(1,16) gives the array of 1 to 15

Reshape function shapes the array row-wise into shape 3*5

Transpose the array to get the elements column-wise and shape it into 5*3

Print the result

In [2]:
arr = np.arange(1,16).reshape(3,5).T
arr

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

### 3. Write a Python/Numpy code block that removes from array a any items that are also present in array b
np.setdiff1d(a,b) gives the items from array a that is not present in array b

Assign the result array to variable c

Print the result

In [3]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

c = np.setdiff1d(a,b)
c

array([ 1,  7,  8, 15])

### 4. The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
Print arr to check we are using the same required array

Assigning it to variable arr1, transpose it to get the elements row-wise and the shape changes to 3*5

Use flatten function to transform the multidimensional array to unidimensional array and get the sequence

Print the result

In [4]:
print(arr)
arr1 = arr.T.flatten()
print(arr1)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### TASK 5
Suppress scientific notation np.set_printoptions(suppress = True)

Read the data file from GitHub and convert to a NumPy ndarray object

Be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below with a link to the “raw” version of the file you pushed to your online GitHub repository

Verify you have an ndarray object

In [5]:
import pandas
import numpy as np

nyc_water = pandas.read_csv('https://raw.githubusercontent.com/Aishwarya-Deshmane/DAV-5400/main/M3_Data.csv').to_numpy()

type(nyc_water)

numpy.ndarray

### 5.1 What is the maximum yearly NYC consumption of water in millions of gallons per day?
np.amax gives the maximum value of the given array

Assign the result to variable result1. 'nyc_water[:,2]' notifies the column index 2 of nyc_water dataset

Print the result

In [6]:
result1 = np.amax(nyc_water[:,2])
print('Maximum yearly NYC water consumption in millions of gallons per day is :',result1)

Maximum yearly NYC water consumption in millions of gallons per day is : 1512.0


### 5.2 How many calendar years are represented within this data set? NumPy's shape command is one way to find out
np.shape finds out the shape of array. '(nyc_water)[0]' specifies that we are counting the rows i.e.,number of records of nyc_water dataset. This also gives us the count of calendar years

Assign the function to result2 variable

Print the result

In [7]:
result2 = np.shape(nyc_water)[0]
print('The number of calendar years represented in dataset are :',result2)

The number of calendar years represented in dataset are : 41


### 5.3 What is the mean and the standard deviation of the per capita daily water consumption?
np.mean gives the mean and np.std gives the standard deviation of the array. 'nyc_water[:,3]' specifies that we are getting mean and std of column index 3 from nyc_water dataset

Assign the functions to resultmean and resultstd variables

Print the result

In [8]:
resultmean = np.mean(nyc_water[:,3])
print('Mean of the per capita daily water consumption is :',resultmean)
resultstd = np.std(nyc_water[:,3])
print('Standard deviation of the per capita daily water consumption is :',resultstd)

Mean of the per capita daily water consumption is : 158.41463414634146
Standard deviation of the per capita daily water consumption is : 31.847177467886052


### 5.4 What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.
np.diff gives the difference between each element of array. 'nyc_water[:,1]' specifies that we are getting year to year population difference for column index 1 of nyc_water dataset

Assign the function to pop_diff variable

Print the result

In [9]:
pop_diff = np.diff(nyc_water[:,1])
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5,  97830. ,  75069. ,  50707. ,  38648. ,  30794. ,
         7795. , -37705. , -39523. , -61931. ])